title: Products
sites:
  - default
  - english
propagate: false
template: registration/show
layout: layout
revisions: false
route:
  default: '/prijave/{slug}'
  english: '/registrations/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
  max_depth: 1
